version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.x
    commands:
      - apt-get update && apt-get install -y unzip
      - curl -o terraform.zip https://releases.hashicorp.com/terraform/1.0.11/terraform_1.0.11_linux_amd64.zip
      - unzip terraform.zip
      - mv terraform /usr/local/bin/
  pre_build:
    commands:
      - terraform --version
      - terraform init
  build:
    commands:
      - terraform apply -auto-approve
